name: New Year Greeting

on:
  schedule:
    - cron: '0 0 1 1 *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Add new year greeting to readme
      run: |
        GREETING=$'\n\n## Happy new year!!!\n_Wishing you all the best in 2026!_\n'

        if ! grep -q "Happy new year!!!" README.md; then
          printf "%s" "$GREETING" >> README.md
        else
          echo "New Year greeting already exists in README"
        fi

    - name: Commit and push changes
      run: |
        git config --local user.email "oliwerx12@gmail.com"
        git config --local user.name "${{ github.actor }}"
        git add README.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "ðŸŽ‰ Add Happy New Year 2026 greeting" && git push)
